name: Cypress Tests

on:
  push:
    branches: [ "winge2e_assessment" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        run: npm install

      - name: Set env
        run: |
          echo WING_URL=${{ secrets.WING_URL }} >> $GITHUB_ENV
          echo WING_USERNAME=${{ secrets.WING_USERNAME }} >> $GITHUB_ENV
          echo WING_PASSWORD=${{ secrets.WING_PASSWORD }} >> $GITHUB_ENV
          echo SUPABASE_URL=${{ secrets.SUPABASE_URL }} >> $GITHUB_ENV
          echo SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} >> $GITHUB_ENV

      - name: Run tests
        run: npx cypress run --headless
