name: Cypress Tests

on:
  push:
    branches: [ "main" ]

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install
        run: npm install

      - name: Set env
        run: |
          echo TEST_USER=${{ secrets.TEST_USER }} >> $GITHUB_ENV
          echo TEST_PASS=${{ secrets.TEST_PASS }} >> $GITHUB_ENV
          echo CRM_URL=${{ secrets.CRM_URL }} >> $GITHUB_ENV
          echo CHAT_URL=${{ secrets.CHAT_URL }} >> $GITHUB_ENV

      - name: Run tests
        run: npx cypress run --headless
